OnlineKnittingStore/OnlineKnittingStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('super-secret-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineKnittingStore/carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

OnlineKnittingStore/goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.CatalogView.as_view(), name='index'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/',views.ProductView.as_view(), name='product'),
]

OnlineKnittingStore/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('',  views.IndexView.as_view(), name='index'),
]

OnlineKnittingStore/goods/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    image = models.ImageField(upload_to='goods_images', verbose_name='Изображение',blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в процентах')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Категория')


    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("id",)

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        else:
            return self.price

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'product_slug': self.slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Products, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='goods_images', verbose_name="Изображение")

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def __str__(self):
        return f"{self.product.name} - изображение"

OnlineKnittingStore/goods/views.py
from django.db.models import Q
from django.http import Http404
from django.views.generic import DetailView, ListView

from goods.models import Products, Categories

class CatalogView(ListView):
    template_name = 'goods/catalog.html'
    context_object_name = 'goods'
    paginate_by = 9
    allow_empty = False

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        sort = self.request.GET.get('sort', None)
        query = self.request.GET.get('q', '').strip()

        if category_slug == 'all':
            goods = Products.objects.all()
        elif category_slug == 'sale':
            goods = Products.objects.filter(discount__gt=0)
        else:
            goods = Products.objects.filter(category__slug=category_slug)
            if not goods.exists():
                raise Http404("Товары для этой категории не найдены")

        if query:
            goods = goods.filter(Q(name__icontains=query) | Q(description__icontains=query))

        if sort == 'date_desc':
            goods = goods.order_by('-id')  # новые → старые
        elif sort == 'date_asc':
            goods = goods.order_by('id')  # старые → новые

        return goods


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_slug = self.kwargs.get('category_slug')

        if category_slug == 'all':
            category_name = 'Все товары'
        elif category_slug == 'sale':
            category_name = 'Распродажа'
        else:
            category = Categories.objects.get(slug=category_slug)
            category_name = category.name

        context['title'] = category_name
        context['category_slug'] = category_slug
        context['search_query'] = self.request.GET.get('q', '')
        context['sort_value'] = self.request.GET.get('sort')
        return context


class ProductView(DetailView):
    model = Products
    context_object_name = 'product'
    template_name = 'goods/product.html'
    slug_url_kwarg = 'product_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        return context

OnlineKnittingStore/goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<section id="catalog" style="height: auto;padding: 95px 0px;">
        <div class="container">
            <div class="row">
                <!-- Панель фильтров -->
                <div class="container my-4">
                    <div class="card p-3">

                        <form method="get" action="{% url 'catalog:index' category_slug %}" class="row gy-2 gx-3 align-items-center">
                            <!-- Категории -->
                            <div class="col-md-8">
                                <label class="form-label fw-semibold mb-2">Категории:</label>
                                <div class="btn-group flex-wrap" role="group">

                                    <a href="{% url 'catalog:index' 'all' %}"
                                       class="btn btn-outline-primary {% if category_slug == 'all' %}active{% endif %}">
                                        Все
                                    </a>

                                    {% for category in categories %}
                                        {% if category.slug != 'all' and category.slug != 'sale' %}
                                            <a href="{% url 'catalog:index' category.slug %}"
                                               class="btn btn-outline-primary {% if category_slug == category.slug %}active{% endif %}">
                                                {{ category.name }}
                                            </a>
                                        {% endif %}
                                    {% endfor %}

                                    <a href="{% url 'catalog:index' 'sale' %}"
                                       class="btn btn-outline-danger {% if category_slug == 'sale' %}active{% endif %}">
                                        Распродажа
                                    </a>
                                </div>
                            </div>

                            <!-- Поиск -->
                            <div class="col-12 col-md-6 col-lg-3">
                                <div class="d-flex mt-2" style="gap: 1rem;">  <!-- gap = 1rem ~ 16px -->
                                    <input type="search"
                                           name="q"
                                           value="{{ search_query }}"
                                           class="form-control"
                                           placeholder="Поиск"
                                           style="flex: 1;">  <!-- поле занимает всё доступное место -->
                                    <button class="btn btn-primary" type="submit">
                                        Поиск
                                    </button>
                                </div>
                            </div>

                            <!-- Сортировка -->
                            <div class="col-md-4">
                                <label for="sort" class="form-label fw-semibold">Сортировка:</label>
                                <select name="sort" id="sort" class="form-select" onchange="this.form.submit()">
                                    <option value="" {% if not sort_value %}selected{% endif %}>Без сортировки</option>
                                    <option value="date_desc" {% if sort_value == 'date_desc' %}selected{% endif %}>
                                        По дате (новые → старые)
                                    </option>
                                    <option value="date_asc" {% if sort_value == 'date_asc' %}selected{% endif %}>
                                        По дате (старые → новые)
                                    </option>
                                </select>
                            </div>

                        </form>
                    </div>
                </div>

                {% for product in goods %}
                    <!-- Карта товара -->
                    <div class="col-md-6 col-lg-4 text-center mb-4">

                        <div class="card p-3 p-3 h-100" style="max-height: 750px; display: flex; flex-direction: column;">
                            {% with product.images.first as main_img %}
                                {% if main_img %}
                                    <img src="{{ main_img.image.url }}" class="card-img-top"  style="height: 350px; object-fit: cover;" alt="{{ product.name }}">
                                {% else %}
                                    <img src="{% static 'images/no_photo.jpg' %}" class="card-img-top"  style="height: 350px; object-fit: cover;" alt="...">
                                {% endif %}
                            {% endwith %}
                            <div class="card-body d-flex flex-column justify-content-between">
                                <a href="{% url 'catalog:product' product.slug %}">
                                    <p class="card-title text-truncate mb-1">{{ product.name }}</p>
                                </a>
                                <p class="card-text text-truncate mb-2" style="max-height: 40px; overflow: hidden;">
                                    {{ product.description }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center mt-auto">
                                    {% if product.discount %}
                                        <p><s>{{ product.price }} ₽</s></p>
                                        <p><strong>{{ product.sell_price }} ₽</strong></p>
                                        <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                                    {% else %}
                                        <p><strong>{{ product.price }} ₽</strong></p>
                                    {% endif %}
                                    <a href="{% url 'cart:cart_add' %}" class="btn add-to-cart" data-product-id="{{ product.id }}">
                                        {% csrf_token %}
                                        <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon"
                                             width="32" height="32">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    <!-- Пагинация -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                 <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                    <a class="page-link" href="
                    {% if page_obj.has_previous %}
                        ?{% change_params page=page_obj.previous_page_number %}
                    {% endif %}">
                        Пред.
                    </a>
                </li>

                <li class="page-item {% if page_obj.number == 1 %}active{% endif %}">
                    <a class="page-link" href="?{% change_params page=1 %}">1</a>
                </li>

                {% if page_obj.number > 4 %}
                    <li class="page-item disabled">
                        <span class="page-link">...</span>
                    </li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                    {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 and page != 1 and page != page_obj.paginator.num_pages %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">
                                {{ page }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.number < page_obj.paginator.num_pages|add:-3 %}
                    <li class="page-item disabled">
                        <span class="page-link">...</span>
                    </li>
                {% endif %}

                {% if page_obj.paginator.num_pages > 1 %}
                    <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages %}active{% endif %}">
                        <a class="page-link"
                           href="?{% change_params page=page_obj.paginator.num_pages %}">
                            {{ page_obj.paginator.num_pages }}
                        </a>
                    </li>
                {% endif %}

                <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                    <a class="page-link" href="
                    {% if page_obj.has_next %}
                        ?{% change_params page=page_obj.next_page_number %}
                    {% endif %}">
                        След.
                    </a>
                </li>
            </div>
        </ul>
    </nav>
</section>
{% endblock content %}

OnlineKnittingStore/goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<div class="container" style="margin-top: 150px;">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 p-4 rounded bg-white shadow-sm">
            <div class="row g-5">
                <!-- Галерея фото -->
                <div class="col-lg-6">
                    <div class="border rounded p-3 mb-3">
                        {% with product.images.first as main_img %}
                            {% if main_img %}
                                    <div class="main-image-wrapper">
                                        <img id="mainImage" src="{{ main_img.image.url }}"
                                             class="main-image"
                                             alt="{{ product.name }}">
                                    </div>
                            {% else %}
                                    <div class="main-image-wrapper">
                                        <img id="mainImage" src="{% static 'images/no_photo.jpg' %}"
                                             class="main-image"
                                             alt="...">
                                    </div>
                            {% endif %}
                        {% endwith %}
                    </div>

                    <div class="d-flex gap-3 flex-wrap">
                        {% for img in product.images.all %}
                        <img src="{{ img.image.url }}"
                             class="img-thumbnail rounded small-thumb"
                             style="width: 100px; cursor: pointer;"
                             onclick="document.getElementById('mainImage').src=this.src;">
                        {% endfor %}
                    </div>
                </div>

                <!-- Инфо товара -->
                <div class="col-lg-6">
                    <h2 class="fw-bold mb-3">{{ product.name }}</h2>
                    {% if product.discount %}
                        <p><s>{{ product.price }} ₽</s></p>
                        <h4 class="text-primary mb-4">
                            <p><strong>{{ product.sell_price }} ₽</strong></p>
                        </h4>
                        <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                    {% else %}
                        <h4 class="text-primary mb-4">
                            <p><strong>{{ product.price }} ₽</strong></p>
                        </h4>
                    {% endif %}
                    <div class="mb-4">
                         <label class="form-label fw-semibold mb-2">Количество:</label>

                        <div class="qty-wrapper">
                            <button class="qty-btn" onclick="changeQty(-1)">−</button>

                            <input id="qty"
                                   type="number"
                                   class="qty-input"
                                   value="1"
                                   min="1"
                                   max="{{ product.quantity }}">

                            <button class="qty-btn" onclick="changeQty(1)">+</button>
                        </div>

                        <div class="mt-2 small text-muted">
                             В наличии: <b>{{ product.quantity }}</b> шт.
                        </div>
                    </div>

                    <a href="{% url 'cart:cart_add' %}" class="btn btn-primary btn-lg px-4 mt-2 w-100 add-to-cart" data-product-id="{{ product.id }}">
                        {% csrf_token %}
                        <i class="fa fa-shopping-cart me-2"></i> Добавить в корзину
                    </a>

                    <hr class="my-4">
                    <h5 style="font-weight: 700;">О товаре</h5>
                    <p class="lh-lg">
                        {{ product.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}