OnlineKnittingStore/OnlineKnittingStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('super-secret-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineKnittingStore/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('',  views.IndexView.as_view(), name='index'),
]

OnlineKnittingStore/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(), name='create_order'),
]

OnlineKnittingStore/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

OnlineKnittingStore/orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        else:
            return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name='Пользователь', default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=40, default='В обработке', verbose_name='Статус заказа')

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Продукт', default=None)
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'

OnlineKnittingStore/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, null=True, blank=True, verbose_name='Номер телефона')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

OnlineKnittingStore/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

OnlineKnittingStore/users/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, TemplateView

from carts.models import Cart
from orders.models import OrderItem, Order
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from users.mixins import CacheMixin


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key
        response = super().form_valid(form)

        if session_key:
            Cart.objects.filter(
                session_key=session_key,
                user__isnull=True
            ).update(user=self.request.user)

        return response

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

        return HttpResponseRedirect(self.success_url)


class UserProfileView(CacheMixin, LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Личный кабинет'
        orders = (
            Order.objects.filter(user=self.request.user).prefetch_related(
                Prefetch(
                    'orderitem_set',
                    queryset=OrderItem.objects.select_related('product')
                )
            )
            .order_by('-id')
        )
        context['orders'] = self.set_get_cache(orders, f"user_{self.request.user.id}_orders", 60)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_staff or request.user.is_superuser:
            return redirect('/super-secret-admin/')
        return super().dispatch(request, *args, **kwargs)



class UserCartView(TemplateView):
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Корзина'
        return context

OnlineKnittingStore/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<section id="login" style="height: auto;padding: 105px 0px;">
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                                <label for="id_username" class="form-label">Имя пользователя</label>
                                <input type="text" class="form-control"
                                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                       name="username" id="id_username" placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль" required>
                        </div>
                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger py-2">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'user:registration' %}">Создать аккаунт</a>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

OnlineKnittingStore/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<section id="profile" style="height: auto;padding: 105px 0px;">
    <div class="container">

        <div class="row gy-4">

            <!-- ПРОФИЛЬ -->
            <div class="col-lg-4">
                <div class="card shadow-sm border-0">
                    <div class="card-body text-center">

                        <h4 class="mb-4">Профиль пользователя</h4>

                        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if user.image %}
                                <img src="{{ user.image.url }}"
                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                     style="max-width: 150px;">
                            {% else %}
                                <img src="{% static 'deps/icons/baseavatar.png' %}"
                                    alt="Аватар пользователя" class="rounded-circle mb-3"
                                    style="width: 140px; height: 140px; object-fit: cover;">
                            {% endif %}
                            <input type="file" class="form-control mb-3" accept="id_image"
                                name='image'
                                accept="image/*">
                            {% if form.image.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                 {% endif %}
                            </div>

                            <div class="mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                            </div>

                            <div class="mb-4">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                            </div>

                            <button class="btn btn-dark w-100">
                                Сохранить изменения
                            </button>
                            <a href="{% url 'users:logout' %}" class="btn btn-outline-danger w-100">
                                Выйти из аккаунта
                            </a>
                        </form>
                    </div>
                </div>
            </div>

            <!-- КОРЗИНА -->
            <div class="col-lg-8">
                <div class="card shadow-sm border-0 mb-4">
                    <div class="card-body">

                        <!-- Заголовок -->
                        <h4 class="mb-4">Корзина</h4>

                        <!-- Товары корзины -->
                        <div class="container" id="cart-items-container">
                            {% include 'carts/includes/included_cart.html' %}
                        </div>

                        <!-- Кнопка -->
                        {% if carts %}
                            <div class="d-grid mt-4">
                                <a class="btn btn-dark btn-lg"
                                   href="{% url 'orders:create_order' %}">
                                    Оформить заказ
                                </a>
                            </div>
                        {% endif %}

                    </div>
                </div>

                <!-- ЗАКАЗЫ -->
                <div class="card shadow-sm border-0">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <h4 class="mb-0">Мои заказы</h4>
                        </div>
                        <!-- ЗАКАЗ -->
                        {% for order in orders %}
                            <div class="card mb-3 border-0 shadow-sm">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between align-items-center mb-3">
                                        <div>
                                            <strong>Заказ {{ order.id }}</strong>
                                            <span class="text-muted ms-2">{{ order.created_timestamp }}</span>
                                        </div>
                                        <span class="badge bg-warning px-3 py-2">
                                            {{order.status}}
                                        </span>
                                    </div>

                                    <div class="table-responsive">
                                        <table class="table align-middle mb-3">
                                            <thead class="table-light">
                                                <tr>
                                                    <th>Товар</th>
                                                    <th class="text-center">Кол-во</th>
                                                    <th class="text-end">Цена</th>
                                                    <th class="text-end">Сумма</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td>{{ item.product.name }}</td>
                                                        <td class="text-center">{{ item.quantity }}</td>
                                                        <td class="text-end">{{ item.price }}</td>
                                                        <td class="text-end fw-semibold">{{ item.products_price }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

OnlineKnittingStore/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<section id="registration" style="height: auto;padding: 105px 0px;">
      <div class="row">
          <div class="container mt-5">
              <div class="row justify-content-center">
                  <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                      <h2 class="text-center mb-4">Регистрация</h2>
                          <form action="{% url 'user:registration' %}" method="post">
                          {% csrf_token %}
                              <div class="row">
                                  <div class="col-md-6 mb-3">
                                      <label for="id_first_name" class="form-label">Имя*</label>
                                      <input type="text" class="form-control" id="id_first_name"
                                             value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                             name="first_name"
                                             placeholder="Введите ваше имя" required>
                                      {% if form.first_name.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                      {% endif %}
                                  </div>
                                  <div class="col-md-6 mb-3">
                                      <label for="id_last_name" class="form-label">Фамилия*</label>
                                      <input type="text" class="form-control" id="id_last_name"
                                             value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                             name="last_name"
                                             placeholder="Введите вашу фамилию" required>
                                      {% if form.last_name.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                      {% endif %}
                                  </div>
                                  <div class="col-md-6 mb-3">
                                      <label for="id_username" class="form-label">Имя пользователя*</label>
                                      <input type="text" class="form-control" id="id_username"
                                             value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                             name="username"
                                             placeholder="Введите ваше имя пользователя" required>
                                      {% if form.username.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                      {% endif %}
                                  </div>
                                  <div class="col-md-6 mb-3">
                                      <label for="id_email" class="form-label">Email*</label>
                                      <input type="email" class="form-control" id="id_email"
                                             value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                             name="email"
                                             placeholder="Введите ваш email" required>
                                      {% if form.email.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                      {% endif %}
                                  </div>
                                  <div class="col-md-6 mb-3">
                                      <label for="id_password1" class="form-label">Пароль*</label>
                                      <input type="password" class="form-control" id="id_password1"
                                             value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                             name="password1"
                                             placeholder="Введите пароль" required>
                                      {% if form.password1.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                      {% endif %}
                                  </div>
                                  <div class="col-md-6 mb-3">
                                      <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                      <input type="password" class="form-control" id="id_password2"
                                             value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                             name="password2"
                                             placeholder="Подтвердите пароль" required>
                                      {% if form.password2.errors %}
                                          <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                      {% endif %}
                                  </div>
                              </div>
                              <button type="submit"
                                    class="btn btn-dark btn-block">Зарегистрироваться</button>
                          </form>
                  </div>
              </div>
          </div>
    </div>
</section>
{% endblock content %}

OnlineKnittingStore/users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}

{% block local_css %}
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock local_css %}

{% block content %}
<section id="cart" style="padding: 95px 0;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">

                <div class="card p-4 shadow-sm">

                    <!-- Заголовок -->
                    <h4 class="mb-4 text-center">Корзина</h4>
                    <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                        {% include 'carts/includes/included_cart.html' %}
                    </div>

                    <!-- Кнопка -->
                    {% if carts %}
                        <div class="d-grid mt-4">
                            <a class="btn btn-dark btn-lg"
                               href="{% url 'orders:create_order' %}">
                                Оформить заказ
                            </a>
                        </div>
                    {% endif %}

                </div>

            </div>
        </div>
    </div>
</section>
{% endblock content %}