OnlineKnittingStore/OnlineKnittingStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('super-secret-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineKnittingStore/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('',  views.IndexView.as_view(), name='index'),
]

OnlineKnittingStore/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

OnlineKnittingStore/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load goods_tags %}
{% load carts_tags %}

<html lang="ru">

{% user_carts request as carts %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'deps/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic">
    <link rel="stylesheet" href="{% static 'deps/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">

    <!-- Локальные стили -->
    {% block local_css %} {% endblock local_css %}

    <!-- Иконки для разных платформ -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple_touch_yarn_ball_180x180.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon_yarn_ball_32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon_yarn_ball_16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{{ title }}</title>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container"><a class="navbar-brand js-scroll-trigger" href="{% url 'main:index' %}">Вязаные изделия</a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-align-justify"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'main:index' %}#about">Информация</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'main:index' %}#delivery">Доставка</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'catalog:index' 'all' %}">Каталог</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'main:index' %}#contact">Контакты</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:users_cart' %}#cart">
                        Корзина ( <span id="goods-in-cart-count">{{ carts.total_quantity }}</span> )</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:profile' %}">
                                Профиль
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">
                                Войти
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    {% tag_categories as categories %}



    {% block content %}{% endblock content %}
    {% block footer %}{% endblock footer%}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'deps/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script src="{% static 'js/creative.js' %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>

</body>